### ISSUE TITLE
Why this Docker build over the standard Anvil one?

### ISSUE THREAD

**Issue by ikb42** [vsimonian/docker-anvil-connect#2]
I am having problems with the std anvil one, I need to install a private repo (via package.json in connect) but I am getting errors about no SSH installed on the std anvil connect docker image.

Thanks!

**Comment by adalinesimonian** [comment]
Regarding the issue of ssh not being installed, it sounds like it is not directly related to anything specific that's different between this image and the official one. From what I understand so far, to fix the problem, you should be able to do something like this in your Dockerfile:

If not using package.json:

``` Dockerfile
FROM vartan/anvil-connect:0.1.58

# Install private package locally
# Keep only the build dependencies you need, remove ones you don't
RUN apk add --update ssh ca-certificates git python make g++ gcc && \
    npm install @scope/my-private-package && \
    rm -rf /root/.npm && \
    apk del ssh ca-certificates git python make g++ gcc && \
    rm -rf /var/cache/apk/*

# Copy custom files (for example)
COPY protocols /connect/protocols
COPY providers /connect/providers

# Copy Anvil Connect configuration
COPY config.json /connect/config.json
```

If using package.json:

``` Dockerfile
FROM vartan/anvil-connect:0.1.58

# Copy package.json
COPY package.json /connect/package.json

# Install private package locally
# Keep only the build dependencies you need, remove ones you don't
RUN apk add --update ssh ca-certificates git python make g++ gcc && \
    npm install && \
    rm -rf /root/.npm && \
    apk del ssh ca-certificates git python make g++ gcc && \
    rm -rf /var/cache/apk/*

# Copy custom files (for example)
COPY protocols /connect/protocols
COPY providers /connect/providers

# Copy Anvil Connect configuration
COPY config.json /connect/config.json
```

If ssh is used during runtime, then remove `ssh` from the `apk del` line.

**Comment by adalinesimonian** [comment]
Closing this issue as it's been 3 weeks. If you have any further questions, feel free to open a new issue, or if I haven't answered your question correctly, feel free to re-open.
